### ISSUE TITLE
zopen audit  FSUM7329 <(command) and >(command) not implemented

### ISSUE THREAD

**Issue by gngrossi** [ZOSOpenTools/metaport#55]
11:37:33 RC=(4) [SYSA] bash-5.2$ zopen audit -v
VERBOSE: Obtained vulnerability json cache.
VERBOSE: Found all installed packages.
/hewitt/zopentools/zopen_repo/usr/local/bin/zopen-audit 154: FSUM7329 <(command) and >(command) not implemented

11:38:12 RC=(0) [SYSA] bash-5.2$ zopen audit
/hewitt/zopentools/zopen_repo/usr/local/bin/zopen-audit 154: FSUM7329 <(command) and >(command) not implemented

**Comment by IgorTodorovskiIBM** [comment]
Looks like we've added some bash'isms into the script. FYI @KeplerBoyce

**Comment by gngrossi** [comment]
Should I remove the zopen_vulnerability.json file?

bash-5.2$ pwd;ls -l
/hewitt/zopentools/zopen_repo/var/cache/zopen
total 704
-rw-r--r--   1 @02858   @ISCICS1  320611 Jun  6 20:07 zopen_releases.json
-rw-r--r--   1 @02858   @ISCICS1     909 Jun  6 20:07 zopen_releases.timestamp
-rw-r--r--   1 @02858   @ISCICS1     906 Jun  7 07:59 zopen_releases.timestamp.current
**-rw-r--r--   1 @02858   @ISCICS1    6561 Jun  6 11:39 zopen_vulnerability.json**

**Comment by IgorTodorovskiIBM** [comment]
You don't have to, we'll make a fix and issue a new release of meta

**Comment by gngrossi** [comment]
Installed  meta-main.20240607_174758.zos

bash-5.2$ zopen audit
/hewitt/zopentools/zopen_repo/usr/local/bin/zopen-audit 154: FSUM7329 <(command) and >(command) not implemented

**Comment by gngrossi** [comment]
Installed meta-main.20240611_213145

bash-5.2$ zopen audit
CVE Summary:
0 vulnerabilities (0 low, 0 moderate, 0 high, 0 critical)

Anything I need to reference in zopen_vulnerability.json or is the stdout what's important?

thanks

**Comment by IgorTodorovskiIBM** [comment]
> Installed meta-main.20240611_213145
> 
> bash-5.2$ zopen audit CVE Summary: 0 vulnerabilities (0 low, 0 moderate, 0 high, 0 critical)
> 
> Anything I need to reference in zopen_vulnerability.json or is the stdout what's important?
> 
> thanks

Great, yes stdout is what is important. `zopen audit` downloads and parses the  zopen_vulnerability.json.
