### ISSUE TITLE
jq: error: Could not open file after upgrading to meta-main.20240723_143733.zos

### ISSUE THREAD

**Issue by gngrossi** [ZOSOpenTools/metaport#58]
![image](https://github.com/user-attachments/assets/5683ffcb-0039-49aa-815a-0aeb563fc84b)

**Comment by IgorTodorovskiIBM** [comment]
Thanks, I think this is a bug in zopen-init: https://github.com/ZOSOpenTools/meta/blob/1227c99ab98a8bd3d2635d40917e1e8c24864616/bin/zopen-init#L427.

**Comment by gngrossi** [comment]
Upgraded to meta-main.20240724_151648.zos...looks good.
